# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fvpn < Formula
  desc "Forest VPN CLI client for macOS, Linux, and Windows"
  homepage "https://github.com/forestvpn/cli"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.5/fvpn_darwin_amd64.tar.gz"
      sha256 "4a7a83d737384023b5e29801e749106800eafb06e925baf6befb5565961931d1"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.5/fvpn_darwin_arm64.tar.gz"
      sha256 "0b75d65fd206f48e4eeec166c9d9b7c811421eedfa9c1c97bfe48cf2d5632c41"

      def install
        bin.install "fvpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.5/fvpn_linux_arm64.tar.gz"
      sha256 "33abf520b88de1853f171ad0835bdaafcbc6c323ecb89b97701884b3009fdff0"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.5/fvpn_linux_amd64.tar.gz"
      sha256 "864ff7354e042edb70053d26c4c0abf908916ba226334925835b500e32d979d6"

      def install
        bin.install "fvpn"
      end
    end
  end

  depends_on "wireguard-tools"

  test do
    system "#{bin}/fvpn version"
  end
end
