# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fvpn < Formula
  desc "Forest VPN CLI client for macOS, Linux, and Windows"
  homepage "https://github.com/forestvpn/cli"
  version "0.1.9-dev.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.9-dev.6/fvpn_darwin_arm64.tar.gz"
      sha256 "25c9b83064f13f290c44c9ecde9818a9566611be2a17956fd5c041e54f334ff3"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.9-dev.6/fvpn_darwin_amd64.tar.gz"
      sha256 "42745a2dc9511b356c708e42da881ab95b9404b6725bade7bd77a7469613a933"

      def install
        bin.install "fvpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.9-dev.6/fvpn_linux_arm64.tar.gz"
      sha256 "737dafd3c216861c619ec4f72b939bb39dec2c11c94886cebcebc2b67d912ed3"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.9-dev.6/fvpn_linux_amd64.tar.gz"
      sha256 "1a2457220515dedf5916e6ec14ef1a81ad5584371d7ccbae78310a040195cfe4"

      def install
        bin.install "fvpn"
      end
    end
  end

  depends_on "wireguard-tools"

  test do
    system "#{bin}/fvpn version"
  end
end
